# Generated by Django 4.2.7 on 2023-12-01 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='height',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weight',
        ),
    ]
