# Generated by Django 4.2.7 on 2023-12-07 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0003_alter_userprofile_managers_remove_userprofile_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('fcm_id', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=20)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
