# Generated by Django 4.2.7 on 2023-12-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0004_userinformations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformations',
            name='gender',
            field=models.BooleanField(),
        ),
    ]
