# Generated by Django 4.2.7 on 2023-12-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0005_alter_userinformations_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformations',
            name='gender',
            field=models.IntegerField(default=0),
        ),
    ]
